/* CAM NGUYEN 1000952534
   TANMAY SARDESAI 1001094616*/
   
USE Library_Catalog;


/*Drop Foreign keys*/
ALTER TABLE BOOK DROP FOREIGN KEY FK_BOOK_ITEM_book_id;

ALTER TABLE MEDIA DROP FOREIGN KEY FK_MEDIA_ITEM_media_id;

ALTER TABLE CD DROP FOREIGN KEY FK_CD_MEDIA_media_id;

ALTER TABLE DVD DROP FOREIGN KEY FK_DVD_MEDIA_media_id;

ALTER TABLE AUTHOR DROP FOREIGN KEY  FK_AUTHOR_BOOK_book_id;

ALTER TABLE AUTHOR DROP FOREIGN KEY FK_AUTHOR_PERSON_person_id;

ALTER TABLE PRODUCERDIRECTOR DROP FOREIGN KEY FK_PRODUCERDIRECTOR_MEDIA_media_id ;

ALTER TABLE PRODUCERDIRECTOR DROP FOREIGN KEY FK_PRODUCERDIRECTOR_PERSON_person_id;

ALTER TABLE ARTIST DROP FOREIGN KEY FK_ARTIST_MEDIA_media_id;

ALTER TABLE ARTIST DROP FOREIGN KEY FK_ARTIST_PERSON_person_id;

ALTER TABLE REVIEW DROP FOREIGN KEY FK_REVIEW_ITEM_item_id;

ALTER TABLE REVIEW DROP FOREIGN KEY FK_REVIEW_LIBUSER_user_id;

ALTER TABLE WRITESREVIEW DROP FOREIGN KEY FK_WRITESREVIEW_ITEM_item_id ;

ALTER TABLE WRITESREVIEW DROP FOREIGN KEY  FK_WRITESREVIEW_LIBUSER_user_id;

ALTER TABLE WRITESREVIEW DROP FOREIGN KEY  FK_WRITESREVIEW_REVIEW_review_num;

ALTER TABLE RATES DROP FOREIGN KEY FK_RATES_LIBUSER_user_id;

ALTER TABLE RATES DROP FOREIGN KEY FK_RATES_ITEM_item_id;

ALTER TABLE ITEM DROP FOREIGN KEY FK_RECCOMEND_ITEM_recommended_id;

ALTER TABLE ITEM DROP FOREIGN KEY FK_ITEM_LIBUSER_user_id ;

ALTER TABLE ITEM DROP FOREIGN KEY FK_ITEM_PERSON_publisher_id;

ALTER TABLE ITEM DROP FOREIGN KEY FK_ITEM_GENRE_genre_id ;

/* Drop tables*/

DROP VIEW RATINGS_VIEW;

DROP TABLE ARTIST;

DROP TABLE PRODUCERDIRECTOR;

DROP TABLE RATES;

DROP TABLE WRITESREVIEW;

DROP TABLE AUTHOR;

DROP TABLE CD;

DROP TABLE PERSON;

DROP TABLE DVD;

DROP TABLE BLURAY;

DROP TABLE BOOK;

DROP TABLE ITEM;

DROP TABLE GENRE;

DROP TABLE LIBUSER;

DROP TABLE MEDIA;

DROP TABLE REVIEW;
